swagger: "2.0"

info:
  version: "0.0.1"
  title: UST TRAINING API
  description: This specification is for the UST Training Portal. Here you can find informatiion about UST Trainings and openings.
  
  contact: 
    name: UST
    url: https://www.ust-global.com
    email: admin@ust-global.com
  
  license:
    name: GNU
    url: https://www.ust-global.com
    
host: localhost:3000
basePath: /v1/
schemes:
  - http
  - https
  
consumes:
  - application/json
  #format of the responses to the client
produces: 
  - application/json
  
tags:
  - name: Trainings
    description: Refer to trainings that are offered by UST
    
  - name: Jobs
    description: Refer to trainings that are offered by UST
  - name: Services
    description: Refer to trainings that are offered by UST  
    
externalDocs:
  description: This is an external doc
  url: https://www.developer.ust-global.com/docs
  
paths:
#api name ustapi
  /usttrainings:
    get:
      summary: This is a get api for trainings list
      description: In this page you can find list of trainings and job provided by ust
      security:
        #array elements needed only in case of oauth
        - KeySecurity: []
        
      tags:
        - Trainings
        - Jobs
        - Services
        
      #parameters: There are no parameters for this
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Trainings"
        "400":
          description: when a training is not found
          schema:
            $ref: "#/definitions/GeneralError"
  
  
#Definition
definitions:
  GeneralError:
    required:
      - message
    properties:
      message:
         type: string
         
  #Not Found Error
  NotFoundError:
    required:
      - message
      - hint
    properties:
      message:
        type: string
      hint:
        type: string
        
  #trainings
  Trainings:
    required:
      - name
      - description
      - type
      - numberOfDays
    properties:
      name:
        type: string
      description:
        type: string
      type:
        type: string
        enum: 
          - database
          - api training
          
  deliverables:
    types: array
    items:
      $ref: "#/definitions/Location"
      
        
  Location:
    required:
      - type
      - role
    properties:
      type:
        type: string
      role:
        type: string
        

parameters:
  IdInPath:
    name: id
    in: path
    type: string
    required: true
    
securityDefinitions:
  keySecurity:
    type: apiKey
    in: query
    name: api_key
          